// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFgWReasPyZtQuJZM909JDrbuZNSONZ74',
    appId: '1:602253872500:web:a2932afb75e7bececfb021',
    messagingSenderId: '602253872500',
    projectId: 'esaferide',
    authDomain: 'esaferide.firebaseapp.com',
    storageBucket: 'esaferide.firebasestorage.app',
    measurementId: 'G-6P98SQ3JHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaWV9zF0-5V3pvz7VbXESxinZVLCPAamA',
    appId: '1:602253872500:android:00a64248fec0b855cfb021',
    messagingSenderId: '602253872500',
    projectId: 'esaferide',
    storageBucket: 'esaferide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeH3jpAnLqyE_gLlYtFDk85bjDGJxlZ-w',
    appId: '1:602253872500:ios:34c2ef7ab5e01b4dcfb021',
    messagingSenderId: '602253872500',
    projectId: 'esaferide',
    storageBucket: 'esaferide.firebasestorage.app',
    androidClientId: '602253872500-t76u75ol0cie67ma66rd28s27ji0qi2c.apps.googleusercontent.com',
    iosClientId: '602253872500-9lgqrjr23mrgr34q457ctt1m9b5tmrrp.apps.googleusercontent.com',
    iosBundleId: 'com.example.esaferide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeH3jpAnLqyE_gLlYtFDk85bjDGJxlZ-w',
    appId: '1:602253872500:ios:34c2ef7ab5e01b4dcfb021',
    messagingSenderId: '602253872500',
    projectId: 'esaferide',
    storageBucket: 'esaferide.firebasestorage.app',
    androidClientId: '602253872500-t76u75ol0cie67ma66rd28s27ji0qi2c.apps.googleusercontent.com',
    iosClientId: '602253872500-9lgqrjr23mrgr34q457ctt1m9b5tmrrp.apps.googleusercontent.com',
    iosBundleId: 'com.example.esaferide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFgWReasPyZtQuJZM909JDrbuZNSONZ74',
    appId: '1:602253872500:web:697a8475af328c00cfb021',
    messagingSenderId: '602253872500',
    projectId: 'esaferide',
    authDomain: 'esaferide.firebaseapp.com',
    storageBucket: 'esaferide.firebasestorage.app',
    measurementId: 'G-14JGXEDPGB',
  );
}
